nodeVersion: 24.15.0
pmOnFail: download
packages:
  - docs

catalog:
  '@types/node': ^26.1.2
  react: 19.3.0
  react-dom: 19.3.0
  typescript: 7.0.2

allowBuilds:
  '@scarf/scarf': false
  core-js: false
  esbuild: true
  keytar: false
  oxc-resolver: true
  puppeteer: false
  sharp: true
minimumReleaseAgeExclude:
  - '@seshuk/payload-plugin-tooling'
  - '@payloadcms/db-sqlite@4.0.0-beta.0'
  - '@payloadcms/drizzle@4.0.0-beta.0'
  - '@payloadcms/graphql@4.0.0-beta.0'
  - '@payloadcms/next@4.0.0-beta.0'
  - '@payloadcms/plugin-cloud-storage@4.0.0-beta.0'
  - '@payloadcms/plugin-ecommerce@4.0.0-beta.0'
  - '@payloadcms/plugin-import-export@4.0.0-beta.0'
  - '@payloadcms/plugin-mcp@4.0.0-beta.0'
  - '@payloadcms/plugin-multi-tenant@4.0.0-beta.0'
  - '@payloadcms/plugin-search@4.0.0-beta.0'
  - '@payloadcms/plugin-seo@4.0.0-beta.0'
  - '@payloadcms/plugin-stripe@4.0.0-beta.0'
  - '@payloadcms/storage-r2@4.0.0-beta.0'
  - '@payloadcms/storage-s3@4.0.0-beta.0'
  - '@payloadcms/translations@4.0.0-beta.0'
  - '@payloadcms/ui@4.0.0-beta.0'
  - payload@4.0.0-beta.0
