name: Release
on:
  push:
    tags: ['v*.*.*']
permissions:
  contents: read
jobs:
  release:
    uses: maximseshuk/payload-plugin-tooling/.github/workflows/release.yml@v0.2.3
    permissions:
      contents: write
      id-token: write
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
